import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {calculate,validateData,similarity,usable,resultText,safeUrl} from '../public/engine.js';
import {esc} from '../public/ui.js';
const seed=JSON.parse(await readFile(new URL('../public/data/politics.json',import.meta.url),'utf8'));
// Synthetic positions exist only in tests and never in the published data.
function fixture(){return {schemaVersion:1,title:'Test',version:'test',updated:'2026-10-06',method:{minQuestions:2,minTopics:2},parties:[{id:'a',name:'Alpha',comparable:true},{id:'b',name:'Beta',comparable:true}],sources:[{id:'s',title:'Testquelle',date:'2026-01-01',url:'https://example.org/source'}],questions:[0,1,2].map((i)=>({id:'q'+i,text:'Aussage '+i,topic:'Thema '+i,context:'Kontext',weight:1,active:true,positions:{a:{value:100,evidence:'medium',status:'checked',scope:'party',sources:['s'],locator:'Seite 1',reason:'Test'},b:{value:0,evidence:'medium',status:'checked',scope:'party',sources:['s'],locator:'Seite 2',reason:'Test'}}}))};}
test('distance is symmetric, bounded, and does not coerce missing values',()=>{for(const a of [0,25,50,75,100])for(const b of [0,25,50,75,100]){assert.equal(similarity(a,b),similarity(b,a));assert.ok(similarity(a,b)>=0&&similarity(a,b)<=100);}assert.equal(similarity(75,100),75);assert.equal(similarity(null,0),null);assert.equal(similarity('0',0),null);});
test('neutral and skip have different effects',()=>{let d=fixture();const neutral=calculate(d,{q0:50,q1:50});assert.equal(neutral.ready,true);assert.deepEqual(neutral.rows.map(p=>p.score),[50,50]);assert.deepEqual(neutral.rows.map(p=>p.rank),[1,1]);const skip=calculate(d,{q0:100,q1:null});assert.equal(skip.ready,false);assert.equal(skip.answered,1);});
test('same questions for all parties; gaps never become zero',()=>{const d=fixture();d.questions[0].positions.b.value=null;const r=calculate(d,{q0:0,q1:100,q2:100});assert.equal(r.used.length,2);assert.equal(r.rows[0].score,100);assert.equal(r.rows[1].score,0);assert.equal(r.rows[1].coverage,2);});
test('evidence and attribution gate the calculation',()=>{const p=fixture().questions[0].positions.a;for(const change of [{evidence:'low'},{status:'draft'},{scope:'individual'},{scope:'joint-faction'},{sources:[]},{value:null}])assert.equal(usable({...p,...change}),false);});
test('minimum breadth is required, not just answer count',()=>{const d=fixture();d.questions.forEach(q=>q.topic='Ein Thema');assert.equal(calculate(d,{q0:100,q1:100,q2:100}).ready,false);});
test('ranking cannot depend on party order',()=>{const d=fixture();const a={q0:25,q1:75,q2:50};const first=calculate(d,a).rows;d.parties.reverse();assert.deepEqual(calculate(d,a).rows,first);});
test('weights affect all parties identically',()=>{const d=fixture();d.questions[0].weight=3;const r=calculate(d,{q0:100,q1:0});assert.equal(r.rows[0].score,75);assert.equal(r.rows[1].score,25);});
test('partial coverage and excluded parties are never promoted to a total score',()=>{const d=fixture();d.parties.push({id:'c',name:'Gamma',comparable:false});const r=calculate(d,{q0:100,q1:100});assert.equal(r.rows.at(-1).score,null);assert.equal(r.rows.at(-1).coverage,0);});
test('seed has evidence, visible gaps, and no artificial ranking',()=>{assert.deepEqual(validateData(seed),[]);assert.equal(seed.questions.length,5);assert.equal(seed.parties.length,6);const r=calculate(seed,Object.fromEntries(seed.questions.map(q=>[q.id,100])));assert.equal(r.ready,false);assert.equal(r.common.length,0);assert.ok(r.rows.every(p=>p.score===null));assert.ok(seed.questions.every(q=>q.positions.fwd.value===null&&q.positions.gemeinsam.value===null));assert.equal(seed.questions.find(q=>q.id==='ampelversuch').positions.fdp.scope,'individual');});
test('rejects malformed imports without throwing',()=>{const cases=[null,[],{}, {schemaVersion:1,title:'x',version:'x',updated:'x',parties:[null],sources:[null],questions:[null]}];for(const item of cases)assert.ok(validateData(item).length);for(const field of ['sources','value','evidence','status','scope']){const d=fixture();d.questions[0].positions.a[field]=undefined;assert.ok(validateData(d).length);}const d=fixture();d.questions[0].positions.a.sources=['missing'];assert.ok(validateData(d).length);d.questions[0].weight=NaN;assert.ok(validateData(d).length);});
test('active questions need contrasting evidence, not two agreeing positions',()=>{const d=fixture();d.questions[0].positions.b.value=100;assert.ok(validateData(d).some(s=>s.includes('unterschiedliche')));});
test('unsafe links and content cannot produce markup',()=>{assert.equal(safeUrl('javascript:alert(1)'),false);assert.equal(safeUrl('https://user:secret@example.org'),false);assert.equal(safeUrl('https://www.duedingen.ch/_doc/6933574#page=27'),true);assert.equal(esc('<script>"&'), '&lt;script&gt;&quot;&amp;');});
test('shared result identifies version and contains no individual answer values',()=>{const d=fixture();const text=resultText(d,{q0:75,q1:25});assert.ok(text.includes('Datenversion: test'));assert.ok(text.includes('Alpha: 50 %'));assert.ok(!text.includes('q0'));assert.ok(!text.includes('75'));});
